# 1. Define Research Goal

We want to train a model that's able to classify movie reviews into a positive and a negative class.

First, we need to import all python libraries that we need.

In [1]:
import pandas as pd
import numpy as np
import pickle
from pathlib import Path

from keras.preprocessing.text import Tokenizer
from sklearn.preprocessing import LabelBinarizer
from keras.models import Sequential
from keras import metrics
from keras.layers import Activation, Dense, Dropout
import sklearn.datasets as skds
from sklearn import metrics

import matplotlib.pyplot as plt
import itertools

Using TensorFlow backend.
/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarn

# 2. Retrieve Data
The IMDb Reviews are separated into training and test folders. Each of them has folders for positive and negative reviews.

First, we import all training data to create and train our neural net.

In [ ]:
np.random.seed(1237)

labels = ["pos", "neg"] # contains all category labels that we want to classify
num_labels = 2 # number of labels

path_train = "./resources/aclImdb/train" # path to all reviews that we want to use for developing the model

We load the data by using [scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_files.html). Afterwards, 'files_train' should contain the path and label for each training review.

In [ ]:
files_train = skds.load_files(path_train,load_content=False, categories=labels, encoding="UTF-8") 

file_paths = files_train.filenames
label_names = files_train.target_names
labelled_files_index = files_train.target

Now, we start to read all reviews. Afterwards, data_list should contain tuples of file path, file label and file content for each review.

If this step takes too long, interrupt it and skip to "Load data from pickle"

In [ ]:
data_list = []

for i, file in enumerate(file_paths):
    data_list.append((file,
                      label_names[labelled_files_index[i]],
                      Path(file).read_text(encoding="UTF-8")))

Tuples are transformed into [pandas DataFrame](https://pandas.pydata.org/pandas-docs/version/0.17.0/generated/pandas.DataFrame.from_records.html).

In [ ]:
data_tags=["filename","category","review"]
data = pd.DataFrame.from_records(data_list, columns=data_tags)

## 2.1. Load data from pickle
If reading the data from folders takes too long, you can load the data frame from a serialized pickle file. (Skip this step, if your data frame is already created

In [2]:
with open('resources/train_dataframe.pickle', 'rb') as handle:
    data = pickle.load(handle)

data.head() should show your DataFrame like this:
<img src="resources/dataframe.png" alt="Data Frame Example">

In [3]:
data.head()

filename category  \
0  ./resources/aclImdb/train/pos/11485_10.txt      pos   
1    ./resources/aclImdb/train/neg/6802_1.txt      neg   
2   ./resources/aclImdb/train/pos/7641_10.txt      pos   
3    ./resources/aclImdb/train/neg/9698_1.txt      neg   
4    ./resources/aclImdb/train/neg/3141_2.txt      neg   

                                              review  
0  Zero Day leads you to think, even re-think why...  
1  Words can't describe how bad this movie is. I ...  
2  Everyone plays their part pretty well in this ...  
3  There are a lot of highly talented filmmakers/...  
4  I've just had the evidence that confirmed my s...

# 3. Prepare Data
We now have a Data Frame with all training reviews. For developing the Neural Network we split the DataFrame into training (80%) and development (20%) set. For training, we take review, category and file name from the first 80% of the Data Frame entries.

In [4]:
train_size = int(len(data) * .8) # number of reviews that we take for training

train_reviews = data['review'][:train_size]
train_tags = data['category'][:train_size]

## 3.1. Vectorization
In order to make the reviews interpretable for the Neural Network, we need to tokenize and vectorize the content of the reviews. We use the Keras [Tokenizer](http://faroit.com/keras-docs/1.2.2/preprocessing/text/#tokenizer) to split each review into tokens.

The tokens of each review are weighted corresponding to the selected mode. "Binary" sets a 1 for a token if it appears in the review and 0 if it doesn't appear.

**Now, it's your turn**: Change 'vocab_size' and 'mode' and see what happens to the neural net!

In [5]:
vocab_size = 5000 # determines the size of the vocabulary
mode = 'binary'

tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(train_reviews)

x_train = tokenizer.texts_to_matrix(train_reviews, mode=mode)

Lets see how our train matrix looks like (prints out the first 10 review vectors):

In [6]:
x_train[:10]

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.]])

We can save the tokenizer to a pickle file (for example to load it in the evaluation notebook)

In [7]:
with open('resources/tokenizer/defaulttokenizer.pickle', 'wb') as handle:
    pickle.dump(tokenizer, handle, protocol=pickle.HIGHEST_PROTOCOL)

## 3.2. Label Encoding
We need to encode the categories of our reviews, too. We can do it with a LabelBinarizer that produces an array of all tagged categories.

In [8]:
encoder = LabelBinarizer()
encoder.fit(train_tags)
y_train = encoder.transform(train_tags)

# 4. Explore Data
To get to know the data a little bit better you can count how many positive and negative reviews are there.

In [9]:
val, count = np.unique(y_train, return_counts=True) #count frequency of each number in y_train

for i, c in enumerate(count):
    label = encoder.inverse_transform(val[i])
    print(label, c)

['neg'] 10008
['pos'] 9992


In [10]:
vocab = tokenizer.word_index

# 5. Model Data
Now, we have a matrix of our train input and an array of the related categories. We can build a neural net and train it with x_train and y_train.

In [11]:
optimizer = 'adam'
loss = 'binary_crossentropy'
batch_size = 10
epochs = 10

In [12]:
classifier = Sequential()
#First Hidden Layer
classifier.add(Dense(4, activation='relu', kernel_initializer='random_normal', input_dim=vocab_size))
#Second  Hidden Layer
classifier.add(Dense(4, activation='relu', kernel_initializer='random_normal'))
#Output Layer
classifier.add(Dense(1, activation='sigmoid', kernel_initializer='random_normal'))

Instructions for updating:
Colocations handled automatically by placer.


In [13]:
#Compiling the neural network
classifier.compile(optimizer=optimizer,loss=loss, 
                   metrics =['accuracy'])

In [14]:
#Fitting the data to the training dataset
classifier.fit(x_train,y_train, batch_size=batch_size, epochs=epochs)

Instructions for updating:
Use tf.cast instead.
Epoch 1/10
20000/20000 [==============================] - 2s 102us/step - loss: 0.3711 - acc: 0.8387
Epoch 2/10
20000/20000 [==============================] - 2s 90us/step - loss: 0.2250 - acc: 0.9139
Epoch 3/10
20000/20000 [==============================] - 2s 90us/step - loss: 0.1924 - acc: 0.9273
Epoch 4/10
20000/20000 [==============================] - 2s 90us/step - loss: 0.1745 - acc: 0.9335
Epoch 5/10
20000/20000 [==============================] - 2s 90us/step - loss: 0.1590 - acc: 0.9395
Epoch 6/10
20000/20000 [==============================] - 2s 90us/step - loss: 0.1480 - acc: 0.9453
Epoch 7/10
20000/20000 [==============================] - 2s 90us/step - loss: 0.1393 - acc: 0.9490
Epoch 8/10
20000/20000 [==============================] - 2s 90us/step - loss: 0.1308 - acc: 0.9524
Epoch 9/10
20000/20000 [==============================] - 2s 89us/step - loss: 0.1207 - acc: 0.9570
Epoch 10/10
20000/20000 [==========================

## Save Model

In [15]:
classifier.save('resources/models/defaultModel.h5')

# Classify new Reviews
"classifier" contains our trained neural net. We can use it to classify new film reviews.

In [16]:
own_review = "Greatest film ever"

In [17]:
review_series = pd.Series(own_review)
x_review = tokenizer.texts_to_matrix(review_series)

In [18]:
prob = classifier.predict(x_review)
prob

array([[0.7411214]], dtype=float32)

# 6. Improve Model
After trying the neural net on example reviews we want to know how good it works in general. We use the validation set to evaluate the model.

In [19]:
val_reviews = data['review'][train_size:]
val_tags = data['category'][train_size:]

x_val = tokenizer.texts_to_matrix(val_reviews, mode=mode)
y_val = encoder.transform(val_tags)

Now, we [predict](https://keras.io/models/model/#predict) labels for all test reviews. If the probability for a positive review is more than 0.5, "pos" will be assigned.

In [21]:
probs = classifier.predict(x_val)
y_classified = ['pos' if x > 0.5 else 'neg' for x in probs]

y_true = list(encoder.inverse_transform(y_val)) #transform true encoded categories (0 and 1) to labels (neg and pos)

print(y_classified[:10]) #print first 10 predictions and true labels
print(y_true[:10])

['pos', 'pos', 'neg', 'pos', 'pos', 'pos', 'pos', 'pos', 'neg', 'pos']
['pos', 'pos', 'neg', 'neg', 'neg', 'pos', 'pos', 'pos', 'pos', 'neg']


We create a [confusion matrix](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html) to compare all predicted labels(y_classified) with the true labels(y_true).

In [22]:
cm = metrics.confusion_matrix(y_true, y_classified, labels=["neg", "pos"])
cm

array([[2127,  365],
       [ 330, 2178]])

The confusion matrix gives us all values for further evaluation computations.

In [23]:
tn, fp, fn, tp = cm.ravel()
pre = metrics.precision_score(y_true, y_classified, pos_label='pos')
rec = metrics.recall_score(y_true, y_classified, pos_label='pos')
print("TN, FP, FN, TP ", (tn, fp, fn, tp))
print("Precision ", pre)
print("Recall ", rec)

TN, FP, FN, TP  (2127, 365, 330, 2178)
Precision  0.8564687377113646
Recall  0.868421052631579


Now, you can improve your model by adjusting the configurations. If you think your configurations are ready, you can evaluate them with the test data by using the **EvaluateSentimentClassification** Notebook.

*** 